<?php
/**
 * @package     com_radicalmart_telegram
 * @subpackage  Tests
 * @version     0.1.89
 *















































































































































































































}    exit($test->failed > 0 ? 1 : 0);    $test->run();    $test = new EmailVerificationHelperTest();if (php_sapi_name() === 'cli' && basename(__FILE__) === basename($_SERVER['SCRIPT_FILENAME'] ?? '')) {// Run tests if executed directly}    }        }            $this->failed++;            echo "  ✗ FAIL: {$message} (expected: {$expected}, got: {$actual})\n";        } else {            $this->passed++;            echo "  ✓ {$message}\n";        if ($expected === $actual) {    {    private function assertEquals($expected, $actual, string $message): void    }        }            $this->failed++;            echo "  ✗ FAIL: {$message}\n";        } else {            $this->passed++;            echo "  ✓ {$message}\n";        if ($condition) {    {    private function assertTrue(bool $condition, string $message): void    // ==========================================    // Assertion helpers    // ==========================================    }        return ['valid' => true, 'error' => null];        }            return ['valid' => false, 'error' => 'EMAIL_CYRILLIC_LOCAL'];        if (preg_match('/[\x{0400}-\x{04FF}]/u', $parts[0])) {        $parts = explode('@', $email);        }            return ['valid' => false, 'error' => 'EMAIL_INVALID_FORMAT'];        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {        }            return ['valid' => false, 'error' => 'EMAIL_EMPTY'];        if (empty($email)) {        }            return ['valid' => false, 'error' => 'EMAIL_TOO_LONG'];        if (strlen($email) > 255) {        $email = trim($email);    {    private function mockValidateFormat(string $email): array    }        return str_pad((string) random_int(0, 999999), 6, '0', STR_PAD_LEFT);    {    private function mockGenerateCode(): string    // ==========================================    // Mock implementations (without Joomla)    // ==========================================    }        );            'Cyrillic domain should return valid result structure'            is_array($result) && isset($result['valid']),        $this->assertTrue(        // This may or may not be valid depending on PHP version, just ensure no crash        $result = $this->mockValidateFormat($cyrillicDomain);        $cyrillicDomain = 'test@домен.рф';        // but filter_var may reject raw cyrillic domains        // Cyrillic in domain part is technically allowed after punycode conversion        // Email with international domain (punycode would work, but raw cyrillic might not)        );            'Email over 255 chars should fail with EMAIL_TOO_LONG'            $result['valid'] === false && $result['error'] === 'EMAIL_TOO_LONG',        $this->assertTrue(        $result = $this->mockValidateFormat($longEmail);        $longEmail = str_repeat('a', 250) . '@b.com';        // Too long email        echo "\nTesting validateFormat() edge cases...\n";    {    private function testValidateFormatEdgeCases(): void     */     * Test edge cases for email validation    /**    }        }            );                "Email '{$email}' should have error '{$expectedError}'"                $result['error'],                $expectedError,            $this->assertEquals(            );                "Email '{$email}' should be invalid"                $result['valid'] === false,            $this->assertTrue(            $result = $this->mockValidateFormat($email);        foreach ($invalidEmails as $email => $expectedError) {        ];            'тест@example.com' => 'EMAIL_CYRILLIC_LOCAL', // Cyrillic in local part            'spaces in@email.com' => 'EMAIL_INVALID_FORMAT',            'no@' => 'EMAIL_INVALID_FORMAT',            '@nodomain.com' => 'EMAIL_INVALID_FORMAT',            'not-an-email' => 'EMAIL_INVALID_FORMAT',            '' => 'EMAIL_EMPTY',        $invalidEmails = [        // Invalid emails        }            );                "Email '{$email}' should be valid"                $result['valid'] === true,            $this->assertTrue(            $result = $this->mockValidateFormat($email);        foreach ($validEmails as $email) {        ];            'a@b.co',            'name@subdomain.domain.com',            'user+tag@gmail.com',            'user.name@domain.org',            'test@example.com',        $validEmails = [        // Valid emails        echo "\nTesting validateFormat()...\n";    {    private function testValidateFormat(): void     */     * Test email format validation    /**    }        );            'Code should always be 6 characters (with leading zeros)'            strlen($this->mockGenerateCode()) === 6,        $this->assertTrue(        // This is probabilistic, but we can check format        // Test 3: Code starts with leading zeros if needed        );            'Generated codes should be random (not all same)'            count($unique) > 1,        $this->assertTrue(        $unique = array_unique($codes);        }            $codes[] = $this->mockGenerateCode();        for ($i = 0; $i < 10; $i++) {        $codes = [];        // Test 2: Codes are random (generate 10 and check not all same)        );            'Code should be exactly 6 digits'            preg_match('/^\d{6}$/', $this->mockGenerateCode()) === 1,        $this->assertTrue(        // Test 1: Code is 6 digits        echo "Testing generateCode()...\n";    {    private function testGenerateCode(): void     */     * Test code generation    /**    }        echo "========================================\n\n";        echo "Results: {$this->passed} passed, {$this->failed} failed\n";        echo "\n----------------------------------------\n";        $this->testValidateFormatEdgeCases();        $this->testValidateFormat();        $this->testGenerateCode();        echo "========================================\n\n";        echo "EmailVerificationHelper Tests\n";        echo "\n========================================\n";    {    public function run(): void     */     * Run all tests    /**    private int $failed = 0;    private int $passed = 0;    private array $results = [];{class EmailVerificationHelperTest// Standalone test runner without full Joomla bootstrapnamespace Joomla\Component\RadicalMartTelegram\Tests; */ * Or integrate with PHPUnit if available * Run with: php tests/EmailVerificationHelperTest.php * * Unit tests for EmailVerificationHelper
