<?php
/**
 * @package     com_radicalmart_telegram (site)
 *
 * Сервис бонусов и промокодов - applyPoints, applyPromo, removePromo, createReferralCode
 */

namespace Joomla\Component\RadicalMartTelegram\Site\Service;

\defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
































































































































































































































































































































































































































}    }        return $discount;                }            }                }                    $discount = $template->discount;                } else {                    }                        $discount = PriceHelper::toString($cleanDiscount, 'RUB');                    } else {                        $discount = $cleanDiscount;                    if (strpos($cleanDiscount, '%') !== false) {                    $cleanDiscount = PriceHelper::cleanAdjustmentValue($template->discount);                if (class_exists(PriceHelper::class)) {            if ($template && !empty($template->discount)) {                        $template = $db->setQuery($query)->loadObject();                ->where($db->quoteName('id') . ' = ' . $templateId);                ->from($db->quoteName('#__radicalmart_bonuses_codes'))                ->select(['discount'])            $query = $db->getQuery(true)            $db = Factory::getContainer()->get('DatabaseDriver');        if ($templateId > 0) {                $discount = '';        $templateId = (int) $rmParams->get('bonuses_referral_codes_template_RUB', 0);    {    private function getReferralCodeDiscount($rmParams): string        }        }            $db->updateObject('#__radicalmart_bonuses_codes', $update, 'id');            ];                'customers' => implode(',', array_unique(array_filter($customers)))                'id' => $codeData->id,            $update = (object) [            $db = Factory::getContainer()->get('DatabaseDriver');                        $customers[] = $customerId;        if (!in_array($customerId, $customers)) {                }            $customers = !empty($customers) ? array_filter(array_map('intval', explode(',', $customers))) : [];        if (!is_array($customers)) {        $customers = $codeData->customers ?? [];    {    private function bindCustomerToCode(object $codeData, int $customerId): void        // ============ Private helpers ============        }        ];            'discount' => $discount            'link' => $link,            'code' => $code,            'message' => Text::_('COM_RADICALMART_TELEGRAM_REFERRALS_CODE_CREATED'),            'success' => true,        return [                $discount = $this->getReferralCodeDiscount($rmParams);        // Get discount from template                $link = $linkEnabled ? Uri::root() . '?' . $linkPrefix . '=' . $code : '';        $linkPrefix = $rmParams->get('bonuses_codes_cookies_selector', 'rbc');        $linkEnabled = ((int) $rmParams->get('bonuses_codes_cookies_enabled', 1) === 1);        // Get the created code details                }            ];                'message' => $errorMsg                'success' => false,            return [            $errorMsg = !empty($errors) ? implode(', ', $errors) : Text::_('COM_RADICALMART_TELEGRAM_REFERRALS_CODE_CREATE_ERROR');            $errors = $model->getErrors();        if ($code === false) {                $code = $model->createCode($customCode, 'RUB');                $model->setState('user.id', $userId);                    ->createModel('Referrals', 'Site', ['ignore_request' => true]);            ->getMVCFactory()        $model = $app->bootComponent('com_radicalmart_bonuses')        /** @var \Joomla\Component\RadicalMartBonuses\Site\Model\ReferralsModel $model */        // Use ReferralsModel to create the code                }            $customCode = ''; // Force auto-generation        if (!$canCustomCode) {        $canCustomCode = ((int) $rmParams->get('bonuses_referral_codes_custom_code', 1) === 1);        // Check if custom code is allowed                }            }                ];                    'message' => Text::_('COM_RADICALMART_TELEGRAM_REFERRALS_CODES_LIMIT_REACHED')                    'success' => false,                return [            if ($currentCount >= $codesLimit) {                        $currentCount = (int) $db->setQuery($query)->loadResult();                ->where($db->quoteName('created_by') . ' = ' . (int) $userId);                ->where($db->quoteName('referral') . ' = 1')                ->from($db->quoteName('#__radicalmart_bonuses_codes'))                ->select('COUNT(*)')            $query = $db->getQuery(true)            $db = Factory::getContainer()->get('DatabaseDriver');        if ($codesLimit > 0) {        $codesLimit = (int) $rmParams->get('bonuses_referral_codes_limit', 1);        // Check codes limit                }            ];                'message' => Text::_('COM_RADICALMART_TELEGRAM_REFERRALS_CODES_DISABLED')                'success' => false,            return [        if ((int) $rmParams->get('bonuses_referral_codes_enabled', 1) === 0) {        // Check if referral codes are enabled                $rmParams = ParamsHelper::getComponentParams();        // Get RadicalMart params                }            ];                'message' => Text::_('COM_RADICALMART_TELEGRAM_REFERRALS_NOT_IN_PROGRAM')                'success' => false,            return [        if (!$inChain) {        $inChain = ReferralHelper::inChain($userId);                }            ];                'message' => 'Bonuses component not available'                'success' => false,            return [        if (!class_exists(ReferralHelper::class)) {        // Check if user is in referral chain                }            ];                'message' => Text::_('COM_RADICALMART_TELEGRAM_REFERRALS_LOGIN_REQUIRED')                'success' => false,            return [        if ($userId <= 0) {                $userId = $tgUser['user_id'] ?? 0;        $tgUser = TelegramUserHelper::getCurrentUser();        // Get user                $app = Factory::getApplication();    {    public function createReferralCode(int $chatId, string $customCode = ''): array     */     * @return array Результат создания     * @param string $customCode Пользовательский код (опционально)     * @param int $chatId Telegram chat ID     *      * Создать реферальный код для пользователя    /**        }        ];            'message' => Text::_('COM_RADICALMART_TELEGRAM_PROMO_REMOVED')            'success' => true,        return [                } catch (\Throwable $e) {}            }                CodesHelper::setCookieCode('');            if (class_exists(CodesHelper::class)) {        try {        // Clear cookie                }            $app->setUserState('com_radicalmart.checkout.data', $sessionData);            unset($sessionData['plugins']['bonuses']['codes']);        if (isset($sessionData['plugins']['bonuses']['codes'])) {        $sessionData = $app->getUserState('com_radicalmart.checkout.data', []);        // Clear promo from session                $app = Factory::getApplication();    {    public function removePromo(int $chatId): array     */     * @return array Результат     * @param int $chatId Telegram chat ID     *      * Удалить промокод из сессии    /**        }        ];            'code_id' => $codeData->id ?? 0            ],                'discount_string' => $discountText,                'discount_type' => $discountType,                'discount' => $discountValue,                'applied' => true,            'promo' => [            'code' => $code,            'message' => Text::_('COM_RADICALMART_TELEGRAM_PROMO_APPLIED'),            'success' => true,        return [                $discountText = $discountValue > 0 ? ($isPercent ? "{$discountValue}%" : "{$discountValue} ₽") : '';        $discountType = $isPercent ? 'percent' : 'fixed';        $discountValue = (float) preg_replace('/[^0-9.]/', '', $discountRaw);        $isPercent = (strpos($discountRaw, '%') !== false);        $discountRaw = $codeData->discount ?? '';        // Parse discount value                }            // Cookie setting may fail, not critical        } catch (\Throwable $e) {            CodesHelper::setCookieCode($code);        try {        // Also set cookie for RadicalMart Bonuses                $app->setUserState('com_radicalmart.checkout.data', $sessionData);        $sessionData['plugins']['bonuses']['codes'] = $code;        }            $sessionData['plugins']['bonuses'] = [];        if (!isset($sessionData['plugins']['bonuses'])) {        }            $sessionData['plugins'] = [];        if (!isset($sessionData['plugins'])) {        $sessionData = $app->getUserState('com_radicalmart.checkout.data', []);        // Store code in RadicalMart session                }            $this->bindCustomerToCode($codeData, $customerId);        if ($customerId > 0) {        // Bind customer to code if logged in                }            ];                'debug' => 'Code currency: ' . $codeData->currency . ', expected: RUB'                'message' => Text::_('COM_RADICALMART_TELEGRAM_ERR_PROMO_CURRENCY_MISMATCH'),                'success' => false,            return [        if (!empty($codeData->currency) && $codeData->currency !== 'RUB') {        // Check currency match                }            }                ];                    'debug' => 'Customers limit reached: ' . count($customers) . '/' . $codeData->customers_limit                    'message' => Text::_('COM_RADICALMART_TELEGRAM_ERR_PROMO_LIMIT_REACHED'),                    'success' => false,                return [            if (count($customers) >= (int) $codeData->customers_limit && !in_array($customerId, $customers)) {            }                $customers = !empty($customers) ? array_filter(array_map('intval', explode(',', $customers))) : [];            if (!is_array($customers)) {            $customers = $codeData->customers ?? [];        if (!empty($codeData->customers_limit) && (int) $codeData->customers_limit > 0) {        // Check customers_limit (one-time use codes)                }            ];                'debug' => 'Code requires registration'                'message' => Text::_('COM_RADICALMART_TELEGRAM_ERR_PROMO_REGISTERED_ONLY'),                'success' => false,            return [        if (!empty($codeData->registered_only) && $customerId <= 0) {        // Check registered_only                }            }                ];                    'debug' => 'Code expired on ' . $codeData->expires                    'message' => Text::_('COM_RADICALMART_TELEGRAM_ERR_PROMO_EXPIRED'),                    'success' => false,                return [            if ($now > $expires) {            $expires = new \DateTime($codeData->expires);            $now = new \DateTime();        if (!empty($codeData->expires) && $codeData->expires !== '0000-00-00 00:00:00') {        // Check expiration                }            ];                'debug' => 'Code not found in database'                'message' => Text::_('COM_RADICALMART_TELEGRAM_ERR_PROMO_NOT_FOUND'),                'success' => false,            return [        if (empty($codeData) || $codeData === false) {        // Code not found in database                $codeData = CodesHelper::find($code, 'code');        // Validate promo code via CodesHelper::find()                }            ];                'message' => 'Bonuses component not available'                'success' => false,            return [        if (!class_exists(CodesHelper::class)) {        // Check if CodesHelper is available                $customerId = ($userId > 0) ? (int) $userId : 0;        $userId = $tgUser['user_id'] ?? 0;        $tgUser = TelegramUserHelper::getCurrentUser();        // Get user from TelegramUserHelper                }            ];                'message' => Text::_('COM_RADICALMART_TELEGRAM_ERR_PROMO_REQUIRED')                'success' => false,            return [        if (empty($code)) {                $code = trim($code);                $lang->load('com_radicalmart_telegram', JPATH_SITE);        $lang->load('com_radicalmart_telegram', JPATH_SITE . '/components/com_radicalmart_telegram');        $lang = $app->getLanguage();        // Load language file for translations                $app = Factory::getApplication();    {    public function applyPromo(int $chatId, string $code): array     */     * @return array Результат применения     * @param string $code Промокод     * @param int $chatId Telegram chat ID     *      * Применить промокод    /**        }        ];            'moneyEquivalent' => $moneyEquivalent            'points' => $points,            'message' => $message,            'success' => true,        return [                    : Text::_('COM_RADICALMART_TELEGRAM_POINTS_CLEARED');              . ' (= ' . number_format($moneyEquivalent, 0, ',', ' ') . ' ₽)'              . Text::_('COM_RADICALMART_TELEGRAM_POINTS_UNIT')               . number_format($points, 0, ',', ' ') . ' '             ? Text::sprintf('COM_RADICALMART_TELEGRAM_POINTS_APPLIED') . ': '         $message = $points > 0                }            $moneyEquivalent = PointsHelper::convertToMoney($points, 'RUB');        if ($points > 0 && class_exists(PointsHelper::class)) {        $moneyEquivalent = 0;        // Calculate money equivalent                $app->setUserState('com_radicalmart.checkout.data', $sessionData);        $sessionData['plugins']['bonuses']['points'] = $points;        }            $sessionData['plugins']['bonuses'] = [];        if (!isset($sessionData['plugins']['bonuses'])) {        }            $sessionData['plugins'] = [];        if (!isset($sessionData['plugins'])) {        $sessionData = $app->getUserState('com_radicalmart.checkout.data', []);        // Store points in RadicalMart session (com_radicalmart.checkout.data)                }            $points = 0;        } else {            $points = max(0, $points);            $points = min($points, (int) $availablePoints);            $availablePoints = (float) PointsHelper::getCustomerPoints($customerId);        if (class_exists(PointsHelper::class)) {        // Validate points                }            ];                'message' => Text::_('COM_RADICALMART_ERROR_CUSTOMER_NOT_FOUND')                'success' => false,            return [        if ($customerId <= 0) {                $customerId = (int) $userId;        // In RadicalMart, customer_id equals user_id directly                }            ];                'message' => Text::_('COM_RADICALMART_TELEGRAM_BONUSES_LOGIN_HINT')                'success' => false,            return [        if ($userId <= 0) {                $userId = $tgUser['user_id'] ?? 0;        $tgUser = TelegramUserHelper::getCurrentUser();        // Get user from TelegramUserHelper                $app = Factory::getApplication();    {    public function applyPoints(int $chatId, int $points): array     */     * @return array Результат применения     * @param int $points Количество баллов для списания     * @param int $chatId Telegram chat ID     *      * Применить бонусные баллы к заказу    /**{class BonusesServiceuse Joomla\Component\RadicalMart\Administrator\Helper\PriceHelper;use Joomla\Component\RadicalMart\Administrator\Helper\ParamsHelper;use Joomla\Component\RadicalMartBonuses\Administrator\Helper\ReferralHelper;use Joomla\Component\RadicalMartBonuses\Administrator\Helper\PointsHelper;use Joomla\Component\RadicalMartBonuses\Administrator\Helper\CodesHelper;use Joomla\Component\RadicalMartTelegram\Site\Helper\TelegramUserHelper;use Joomla\CMS\Uri\Uri;use Joomla\CMS\Log\Log;
