<?php
/**
 * @package     com_radicalmart_telegram (site)
 *
 * Сервис оформления заказа - методы checkout, methods, setpvz, setpayment, tariffs
 */

namespace Joomla\Component\RadicalMartTelegram\Site\Service;

\defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Log\Log;




















































































































































































































































































































































































































































































































}    }        ];            ] : null,                'title' => (string)($item->payment->title ?? ''),                'id' => (int)($item->payment->id ?? 0),            'payment' => !empty($item->payment) ? [            ] : null,                'title' => (string)($item->shipping->title ?? ''),                'id' => (int)($item->shipping->id ?? 0),            'shipping' => !empty($item->shipping) ? [            'total' => $total,        return [                }            // final = товары - скидка (без доставки)            $total['sum'] = $total['base'];            // Добавляем числовые значения для JS                        ];                'shipping_string' => $t['shipping_string'] ?? '',                'shipping' => isset($t['shipping']) ? (float)$t['shipping'] : 0,                'final_string' => $t['final_string'] ?? '',                'final' => isset($t['final']) ? (float)$t['final'] : 0,                'discount_string' => $t['discount_string'] ?? '',                'discount' => isset($t['discount']) ? (float)$t['discount'] : 0,                'base_string' => $t['base_string'] ?? '',                'base' => isset($t['base']) ? (float)$t['base'] : 0,            $total = [            $t = $item->total;        if (!empty($item->total)) {        $total = [];    {    private function buildOrderData($item): array        }        return $weight;        }            $weight += $w * $qty;            $w = (float)($prod->weight ?? 0);            $qty = (float)($prod->quantity ?? 1);        foreach ($products as $prod) {        $weight = 0;    {    private function calculateCartWeight(array $products): float        }        ];            'provider' => $provider,            'days' => '',            'cost' => 0,        return [        // Placeholder - actual implementation depends on ApiShip integration    {    private function calculateTariff($cart, int $shippingId, string $pvzId, string $provider, float $lat, float $lon): array        }        return array_values(array_unique($ids));        }            $ids[] = (int)$prod->category_id;        if (!empty($prod->category_id) && is_numeric($prod->category_id)) {        }            }                }                    $ids[] = (int)$c->id;                if (is_object($c) && !empty($c->id)) {                }                    $ids[] = (int)$c['id'];                if (is_array($c) && !empty($c['id']) && is_numeric($c['id'])) {            foreach ($prod->categories as $c) {        if (!empty($prod->categories) && is_array($prod->categories)) {        }            $ids[] = (int)$prod->category->id;        if (!empty($prod->category) && !empty($prod->category->id)) {        $ids = [];    {    private function getProductCategories($prod): array        }        return $methods;                }            // Ignore errors        } catch (\Throwable $e) {                        }                unset($pm);                }                    }                        $pm['disabled'] = true;                    if (!empty($pm['plugin']) && stripos((string)$pm['plugin'], 'telegramstars') !== false) {                foreach ($methods as &$pm) {            if (!$allAllowed) {                        }                }                    }                        }                            break 2;                            $allAllowed = false;                        if (in_array($cid, $excludedCats, true)) {                    foreach ($catIds as $cid) {                if (!empty($excludedCats)) {                }                    }                        break;                        $allAllowed = false;                    if (!$catAllowed) {                    }                        }                            break;                            $catAllowed = true;                        if (in_array($cid, $allowedCats, true)) {                    foreach ($catIds as $cid) {                    $catAllowed = false;                if (!empty($allowedCats)) {                // Check category restrictions                                }                    break;                    $allAllowed = false;                if (!empty($excludedProd) && in_array($pid, $excludedProd, true)) {                }                    break;                    $allAllowed = false;                if (!empty($allowedProd) && !in_array($pid, $allowedProd, true)) {                // Check product restrictions                                $catIds = $this->getProductCategories($prod);                $pid = (int)($prod->id ?? 0);            foreach ($products as $prod) {            $allAllowed = true;            // Check if all products are allowed                        }                return $methods;            if (empty($allowedCats) && empty($excludedCats) && empty($allowedProd) && empty($excludedProd)) {                        $excludedProd = $parseCsv($conf['excluded_products'] ?? '');            $allowedProd = $parseCsv($conf['allowed_products'] ?? '');            $excludedCats = $parseCsv($conf['excluded_categories'] ?? '');            $allowedCats = $parseCsv($conf['allowed_categories'] ?? '');                        };                return array_values(array_unique($out));                }                    }                        $out[] = (int)$v;                    if ($v !== '' && ctype_digit($v)) {                    $v = trim($v);                foreach (explode(',', (string)$csv) as $v) {                $out = [];            $parseCsv = function($csv) {                        $conf = json_decode($paramsJson, true) ?: [];                        }                return $methods;            if ($paramsJson === '') {                        $paramsJson = (string) $db->setQuery($q, 0, 1)->loadResult();                ->where($db->quoteName('element') . ' = ' . $db->quote('telegramstars'));                ->where($db->quoteName('folder') . ' = ' . $db->quote('radicalmart_payment'))                ->where($db->quoteName('type') . ' = ' . $db->quote('plugin'))                ->from($db->quoteName('#__extensions'))                ->select($db->quoteName('params'))            $q = $db->getQuery(true)            $db = Factory::getContainer()->get('DatabaseDriver');        try {    {    private function applyStarsRestrictions(array $methods, array $products): array        }        }            return false;        } catch (\Throwable $e) {            return ((int) $db->setQuery($q, 0, 1)->loadResult()) > 0;                ->bind(':chat', $chatId);                ->where($db->quoteName('chat_id') . ' = :chat')                ->from($db->quoteName('#__radicalmart_telegram_users'))                ->select('COUNT(*)')            $q = $db->getQuery(true)            $db = Factory::getContainer()->get('DatabaseDriver');        try {    {    private function isChatLinked(int $chatId): bool        }        return $iconPath;                }            $iconPath = ltrim($iconPath, '/');            }                $iconPath = $match[1];            if (preg_match('#^https?://[^/]+(/.*?)$#i', $iconPath, $match)) {            // Remove full URL prefix if present            }                $iconPath = substr($iconPath, 0, $hashPos);            if (($hashPos = strpos($iconPath, '#')) !== false) {            // Remove #joomlaImage:// suffix        if ($iconPath) {                }            $iconPath = $media['icon'];        } elseif (is_array($media) && isset($media['icon'])) {            $iconPath = $media->icon;        } elseif (is_object($media) && isset($media->icon)) {            $iconPath = $media->get('icon', '');        if ($media instanceof \Joomla\Registry\Registry) {        $iconPath = '';    {    private function extractIcon($media): string        }        return $out;        }            $out[] = $method;                        }                }                    $method['icon'] = $iconPath;                if ($iconPath) {                $iconPath = $this->extractIcon($m->media);            if (!empty($m->media)) {            // Get icon from media                        ];                'icon' => ''                'description' => isset($m->description) ? (string)$m->description : '',                'plugin' => isset($m->plugin) ? (string)$m->plugin : '',                'disabled' => !empty($m->disabled),                'title' => (string)$m->title,                'id' => (int)$m->id,            $method = [        foreach ($list as $m) {        $out = [];    {    private function mapPaymentMethods(array $list): array        }        return $out;        }            $out[] = $method;                        }                } catch (\Throwable $e) { /* ignore */ }                    }                        $method['providers'] = array_values((array)$providers);                    if (!empty($providers)) {                    $providers = $params->get('providers', []);                    $params = ApiShip::getShippingMethodParams((int)$m->id);                try {            if (!empty($m->plugin) && stripos($m->plugin, 'apiship') !== false) {            // Get providers for ApiShip methods                        ];                'providers' => []                'plugin' => isset($m->plugin) ? (string)$m->plugin : '',                'disabled' => !empty($m->disabled),                'title' => (string)$m->title,                'id' => (int)$m->id,            $method = [        foreach ($list as $m) {        $out = [];    {    private function mapShippingMethods(array $list): array        // ============ Private helpers ============        }        return ['success' => true, 'payment_id' => $paymentId];                $app->setUserState('com_radicalmart.checkout.data', $sessionData);        $sessionData['payment']['id'] = $paymentId;        $sessionData['payment'] = $sessionData['payment'] ?? [];        $sessionData = $app->getUserState('com_radicalmart.checkout.data', []);        // Store in session                }            throw new \RuntimeException(Text::_('COM_RADICALMART_TELEGRAM_ERR_PAYMENT_UNAVAILABLE'));        if (!isset($allowed[$paymentId])) {                }            }                $allowed[(int)$m->id] = true;            foreach ($item->paymentMethods as $m) {        if (!empty($item->paymentMethods)) {        $allowed = [];        // Validate payment method                $item = $model->getItem();        $model->setState('cart.code', (string) $cart->code);        $model->setState('cart.id', (int) $cart->id);        $model = new CheckoutModel();                }            throw new \RuntimeException(Text::_('COM_RADICALMART_TELEGRAM_ERR_CART_EMPTY'));        if (!$cart || empty($cart->id)) {                $cart = $cartSvc->getCart($chatId);        $cartSvc = new CartService();                $app = Factory::getApplication();    {    public function setPayment(int $chatId, int $paymentId): array     */     * @return array     * @param int $paymentId     * @param int $chatId     *      * Установить способ оплаты    /**        }        return ['tariffs' => $tariffs];                }            Log::add('CheckoutService::getTariffs error: ' . $e->getMessage(), Log::WARNING, 'com_radicalmart.telegram');        } catch (\Throwable $e) {            }                $tariffs = ApiShipHelper::getTariffs($shippingId, $lat, $lon, $weight);            if (class_exists(ApiShipHelper::class) && method_exists(ApiShipHelper::class, 'getTariffs')) {        try {        $tariffs = [];        // Get tariffs via ApiShip                $weight = $this->calculateCartWeight($item->products ?? []);        // Calculate weight                }            return ['tariffs' => [], 'error' => 'Shipping method not available'];        if (!$shippingMethod) {                }            }                }                    break;                    $shippingMethod = $m;                if ((int)$m->id === $shippingId) {            foreach ($item->shippingMethods as $m) {        if (!empty($item->shippingMethods)) {        $shippingMethod = null;        // Validate shipping method                $item = $model->getItem();        $model->setState('cart.code', (string) $cart->code);        $model->setState('cart.id', (int) $cart->id);        $model = new CheckoutModel();                }            return ['tariffs' => [], 'error' => 'Cart empty'];        if (!$cart || empty($cart->id)) {                $cart = $cartSvc->getCart($chatId);        $cartSvc = new CartService();    {    public function getTariffs(int $chatId, int $shippingId, float $lat, float $lon): array     */     * @return array     * @param float $lon     * @param float $lat     * @param int $shippingId     * @param int $chatId     *      * Получить тарифы доставки для указанных координат    /**        }        ];            'order' => $this->buildOrderData($item),            'tariff' => $tariffResult,            ],                'address' => $pvzAddress,                'title' => $pvzTitle,                'provider' => $provider,                'id' => $pvzId,            'pvz' => [        return [                $item = $model->getItem();        $model->setState('cart.code', (string) $cart->code);        $model->setState('cart.id', (int) $cart->id);        $model = new CheckoutModel();        // Get updated checkout data                $tariffResult = $this->calculateTariff($cart, $shippingId, $pvzId, $provider, $lat, $lon);        // Calculate shipping tariff                $app->setUserState('com_radicalmart.checkout.data', $sessionData);        ];            'lon' => $lon,            'lat' => $lat,            'address' => $pvzAddress,            'title' => $pvzTitle,            'provider' => $provider,            'id' => $pvzId,        $sessionData['shipping']['pvz'] = [        $sessionData['shipping']['id'] = $shippingId;        $sessionData['shipping'] = $sessionData['shipping'] ?? [];        $sessionData = $app->getUserState('com_radicalmart.checkout.data', []);        // Store PVZ in session                }            throw new \RuntimeException('Missing PVZ parameters');        if ($shippingId <= 0 || $pvzId === '' || $provider === '') {                $lon = (float) ($pvzData['lon'] ?? 0);        $lat = (float) ($pvzData['lat'] ?? 0);        $pvzAddress = trim((string) ($pvzData['address'] ?? ''));        $pvzTitle = trim((string) ($pvzData['title'] ?? ''));        $provider = trim((string) ($pvzData['provider'] ?? ''));        $pvzId = trim((string) ($pvzData['id'] ?? ''));        $shippingId = (int) ($pvzData['shipping_id'] ?? 0);                }            throw new \RuntimeException(Text::_('COM_RADICALMART_TELEGRAM_ERR_CART_EMPTY'));        if (!$cart || empty($cart->id)) {                $cart = $cartSvc->getCart($chatId);        $cartSvc = new CartService();                $app = Factory::getApplication();    {    public function setPvz(int $chatId, array $pvzData): array     */     * @return array Результат с order data     * @param array $pvzData Данные ПВЗ: id, provider, title, address, lat, lon, shipping_id     * @param int $chatId     *      * Установить выбранный ПВЗ и рассчитать стоимость доставки    /**        }        ];            ],                'methods' => $paymentMethods,                'selected' => $selectedPayment,            'payment' => [            ],                'methods' => $shippingMethods,                'selected' => $selectedShipping,            'shipping' => [        return [                $selectedPayment = (!empty($item->payment) && !empty($item->payment->id)) ? (int) $item->payment->id : 0;        $selectedShipping = (!empty($item->shipping) && !empty($item->shipping->id)) ? (int) $item->shipping->id : 0;                $paymentMethods = $this->applyStarsRestrictions($paymentMethods, $item->products ?? []);        // Check Stars payment restrictions                }            unset($pm);            }                }                    $pm['disabled'] = true;                if (!empty($pm['plugin']) && stripos((string)$pm['plugin'], 'telegram') !== false) {            foreach ($paymentMethods as &$pm) {        if (!$hasMap) {        $hasMap = $this->isChatLinked($chatId);        // Disable telegram payments if chat is not linked to user                $paymentMethods = $this->mapPaymentMethods($item->paymentMethods ?? []);        $shippingMethods = $this->mapShippingMethods($item->shippingMethods ?? []);                $item = $model->getItem();        $model->setState('cart.code', (string) $cart->code);        $model->setState('cart.id', (int) $cart->id);        $model = new CheckoutModel();                }            ];                'payment' => ['methods' => [], 'selected' => 0]                'shipping' => ['methods' => [], 'selected' => 0],            return [        if (!$cart || empty($cart->id)) {                $cart = $cartSvc->getCart($chatId);        $cartSvc = new CartService();                $app = Factory::getApplication();    {    public function getMethods(int $chatId): array     */     * @return array ['shipping' => [...], 'payment' => [...]]     * @param int $chatId Telegram chat ID     *      * Получить доступные методы доставки и оплаты    /**{class CheckoutServiceuse Joomla\Plugin\RadicalMartShipping\ApiShip\Extension\ApiShip;use Joomla\Plugin\RadicalMartShipping\ApiShip\Helper\ApiShipHelper;use Joomla\Component\RadicalMartTelegram\Site\Helper\ConsentHelper;use Joomla\Component\RadicalMartTelegram\Site\Helper\TelegramUserHelper;use Joomla\Component\RadicalMart\Administrator\Helper\ParamsHelper;use Joomla\Component\RadicalMart\Administrator\Helper\UserHelper as RMUserHelper;use Joomla\Component\RadicalMart\Site\Model\CheckoutModel;use Joomla\CMS\Uri\Uri;
