<?php
/**
 * Payment Result View - shown after returning from external payment
 */
\defined('_JEXEC') or die;

use Joomla\CMS\Language\Text;
use Joomla\CMS\Uri\Uri;
use Joomla\CMS\Router\Route;

$result = $this->result ?? 'return';
$orderNumber = $this->orderNumber ?? '';

































































































































































</html></body>    </script>        });            } catch(e) {}                document.cookie = 'tg_webapp=1; path=/; max-age=7200; SameSite=Lax';            try {            // Refresh cookie                        }                console.log('Telegram WebApp init error:', e);            } catch(e) {                }                    if (tp.button_text_color) root.style.setProperty('--tg-theme-button-text-color', tp.button_text_color);                    if (tp.button_color) root.style.setProperty('--tg-theme-button-color', tp.button_color);                    if (tp.hint_color) root.style.setProperty('--tg-theme-hint-color', tp.hint_color);                    if (tp.text_color) root.style.setProperty('--tg-theme-text-color', tp.text_color);                    if (tp.bg_color) root.style.setProperty('--tg-theme-bg-color', tp.bg_color);                    const root = document.documentElement;                    const tp = Telegram.WebApp.themeParams || {};                    // Apply Telegram theme                                        Telegram.WebApp.expand();                    Telegram.WebApp.ready();                if (window.Telegram && window.Telegram.WebApp) {            try {        document.addEventListener('DOMContentLoaded', function() {        // Initialize Telegram WebApp    <script>        </div>        </div>            <?php endif; ?>            </button>                <?php echo Text::_('COM_RADICALMART_TELEGRAM_PAYMENT_TRY_AGAIN'); ?>                <span uk-icon="icon: refresh"></span>            <button onclick="window.history.back();" class="uk-button uk-button-danger uk-button-small">            <?php if ($isError): ?>                        </a>                <?php echo Text::_('COM_RADICALMART_TELEGRAM_PAYMENT_GO_CATALOG'); ?>                <span uk-icon="icon: home"></span>            <a href="<?php echo $appUrl; ?>" class="uk-button uk-button-default">                        </a>                <?php echo Text::_('COM_RADICALMART_TELEGRAM_PAYMENT_GO_ORDERS'); ?>                <span uk-icon="icon: file-text"></span>            <a href="<?php echo $ordersUrl; ?>" class="uk-button uk-button-primary">        <div class="payment-result-buttons">        <!-- Buttons -->                <?php endif; ?>        </div>            <?php echo $message; ?>        <div class="payment-result-message">        <?php if ($message): ?>        <!-- Message -->                </div>            <?php echo htmlspecialchars($title, ENT_QUOTES, 'UTF-8'); ?>        <div class="payment-result-title">        <!-- Title -->                </div>            <span uk-icon="icon: <?php echo $iconClass; ?>; ratio: 2" style="color: <?php echo $iconColor; ?>;"></span>        <div class="payment-result-icon" style="background: <?php echo $iconColor; ?>20;">        <!-- Icon -->    <div class="payment-result-container"><body></head>    </style>        }            width: 100%;        .payment-result-buttons .uk-button {        }            max-width: 300px;            width: 100%;            gap: 12px;            flex-direction: column;            display: flex;        .payment-result-buttons {        }            margin-bottom: 30px;            color: var(--tg-theme-hint-color, #666);            font-size: 16px;        .payment-result-message {        }            margin-bottom: 10px;            font-weight: 600;            font-size: 24px;        .payment-result-title {        }            height: 40px;            width: 40px;        .payment-result-icon svg {        }            margin-bottom: 20px;            justify-content: center;            align-items: center;            display: flex;            border-radius: 50%;            height: 80px;            width: 80px;        .payment-result-icon {        }            text-align: center;            padding: 20px;            min-height: 100vh;            justify-content: center;            align-items: center;            flex-direction: column;            display: flex;        .payment-result-container {        }            padding: 0;            margin: 0;            min-height: 100vh;            color: var(--tg-theme-text-color, #222);            background: var(--tg-theme-bg-color, #ffffff);        html, body {    <style>    <script src="<?php echo $root; ?>/templates/yootheme/vendor/assets/uikit/dist/js/uikit-icons.min.js"></script>    <script src="<?php echo $root; ?>/templates/yootheme/vendor/assets/uikit/dist/js/uikit.min.js"></script>    <link rel="stylesheet" href="<?php echo $root; ?>/templates/yootheme/css/theme.css">    <script src="https://telegram.org/js/telegram-web-app.js"></script>    <title><?php echo htmlspecialchars($title, ENT_QUOTES, 'UTF-8'); ?></title>    <meta name="viewport" content="width=device-width, initial-scale=1">    <meta charset="utf-8"><head><html lang="ru"><!DOCTYPE html>?>$ordersUrl = Route::_('index.php?option=com_radicalmart_telegram&view=app&tab=profile', false);$appUrl = Route::_('index.php?option=com_radicalmart_telegram&view=app', false);}    $iconColor = '#1e87f0';    $iconClass = 'info';    $message = '';    $title = Text::_('COM_RADICALMART_TELEGRAM_PAYMENT_RETURN_TITLE');} else {    $iconColor = '#f0506e';    $iconClass = 'close';    $message = Text::_('COM_RADICALMART_TELEGRAM_PAYMENT_ERROR_MESSAGE');    $title = Text::_('COM_RADICALMART_TELEGRAM_PAYMENT_ERROR_TITLE');} elseif ($isError) {    $iconColor = '#32d296';    $iconClass = 'check';        : Text::_('COM_RADICALMART_TELEGRAM_PAYMENT_SUCCESS_TITLE');        ? Text::sprintf('COM_RADICALMART_TELEGRAM_PAYMENT_SUCCESS_MESSAGE', htmlspecialchars($orderNumber))    $message = $orderNumber     $title = Text::_('COM_RADICALMART_TELEGRAM_PAYMENT_SUCCESS_TITLE');if ($isSuccess) {$isError = ($result === 'error');$isSuccess = ($result === 'success');// Determine title and message based on result$root = rtrim(Uri::root(), '/');
