<?php

/**
 * @package     com_radicalmart_telegram
 * @subpackage  Helper
 * @copyright   2024 Cacao.Land
 * @license     GNU General Public License version 2 or later
 */

declare(strict_types=1);

namespace Joomla\Component\RadicalMartTelegram\Site\Helper;

\defined('_JEXEC') or die;

use Joomla\CMS\Component\ComponentHelper;
use Joomla\CMS\Factory;
use Joomla\Database\ParameterType;

/**
 * Helper для интеграции с AcyMailing
 *
 * Позволяет подписывать/отписывать пользователей на рассылку после верификации email
 */
class AcyMailingHelper
{
    /**
     * Проверяет, установлен ли AcyMailing
     */





































































































































































































































































































}    }        return $result;        }            self::updateSubscriptionFlag($chatId, false);        if ($result) {                $result = self::unsubscribe($email);    {    public static function unsubscribeAndUpdateFlag(int $chatId, string $email): bool     */     * @return bool Успех     * @param string $email Email     * @param int $chatId Chat ID     *     * Отписывает пользователя и обновляет флаг в БД    /**    }        return $result;        }            self::updateSubscriptionFlag($chatId, true);        if ($result) {                $result = self::subscribe($email, $name);    {    public static function subscribeAndUpdateFlag(int $chatId, string $email, string $name = ''): bool     */     * @return bool Успех     * @param string $name Имя     * @param string $email Email     * @param int $chatId Chat ID     *     * Подписывает пользователя и обновляет флаг в БД    /**    }        }            LogHelper::error('Failed to update acymailing_subscribed flag: ' . $e->getMessage());        } catch (\Throwable $e) {            $db->setQuery($query)->execute();                ->bind(':chatId', $chatId, ParameterType::INTEGER);                ->bind(':subscribed', $value, ParameterType::INTEGER)                ->where($db->quoteName('chat_id') . ' = :chatId')                ->set($db->quoteName('acymailing_subscribed') . ' = :subscribed')                ->update($db->quoteName('#__radicalmart_telegram_users'))            $query = $db->getQuery(true)            $value = $subscribed ? 1 : 0;            $db = Factory::getContainer()->get('DatabaseDriver');        try {    {    public static function updateSubscriptionFlag(int $chatId, bool $subscribed): void     */     * @param bool $subscribed Подписан или нет     * @param int $chatId Chat ID пользователя     *     * Обновляет флаг acymailing_subscribed в telegram_users    /**    }        }            return [];            LogHelper::error('AcyMailing getLists error: ' . $e->getMessage());        } catch (\Throwable $e) {            return $result;                        }                $result[(int) $list->id] = $list->name;            foreach ($lists as $list) {            $result = [];                        $lists = $listClass->getAll();            $listClass = new \AcyMailing\Classes\ListClass();        try {        }            return [];        if (!self::isAvailable() || !self::initAcyMailing()) {    {    public static function getLists(): array     */     * @return array Массив списков [id => name]     *      * Получает список доступных листов AcyMailing    /**    }        }            return false;            LogHelper::error('AcyMailing isSubscribed error: ' . $e->getMessage());        } catch (\Throwable $e) {            return false;            }                }                    return true;                if ((int) $sub->list_id === $listId && (int) $sub->status === 1) {            foreach ($subscriptions as $sub) {                        $subscriptions = $userClass->getSubscriptionStatus((int) $subscriber->id);            }                return false;            if (!$subscriber) {            $subscriber = $userClass->getOneByEmail($email);            $userClass = new \AcyMailing\Classes\UserClass();        try {        }            return false;        if ($listId <= 0) {        $listId = $listId ?? self::getListId();        }            return false;        if (!self::isAvailable() || !self::initAcyMailing()) {    {    public static function isSubscribed(string $email, ?int $listId = null): bool     */     * @return bool Подписан ли     * @param int|null $listId ID списка     * @param string $email Email пользователя     *     * Проверяет, подписан ли пользователь на список    /**    }        }            return false;            LogHelper::error('AcyMailing unsubscribe error: ' . $e->getMessage());        } catch (\Throwable $e) {            return false;            }                return true;                LogHelper::info('AcyMailing: unsubscribed ' . $email . ' from list ' . $listId);            if ($result) {                        $result = $userClass->unsubscribe((int) $subscriber->id, [$listId]);            }                return true; // Нечего отписывать            if (!$subscriber) {            $subscriber = $userClass->getOneByEmail($email);            $userClass = new \AcyMailing\Classes\UserClass();        try {        }            return false;        if ($listId <= 0) {        $listId = $listId ?? self::getListId();        }            return false;        if (!self::initAcyMailing()) {        }            return false;        if (!self::isEnabled()) {    {    public static function unsubscribe(string $email, ?int $listId = null): bool     */     * @return bool Успех операции     * @param int|null $listId ID списка (если не указан, берётся из настроек)     * @param string $email Email пользователя     *     * Отписывает пользователя от рассылки    /**    }        }            return false;            LogHelper::error('AcyMailing subscribe error: ' . $e->getMessage());        } catch (\Throwable $e) {            }                return false;                LogHelper::warning('AcyMailing: subscribe failed for ' . $email . ' - ' . ($userClass->errors[0] ?? 'unknown error'));            } else {                return true;                LogHelper::info('AcyMailing: subscribed ' . $email . ' to list ' . $listId);            if ($result) {                        $result = $userClass->subscribe($subscriberId, [$listId], true, false);            // Подписываем на список            }                $subscriberId = (int) $subscriber->id;            } else {                }                    return false;                    LogHelper::error('AcyMailing: failed to create subscriber for ' . $email);                if (!$subscriberId) {                $subscriberId = $userClass->save($subscriber);                $subscriber->source = 'telegram_bot';                $subscriber->active = 1;                $subscriber->confirmed = 1; // Уже подтверждён через бота                $subscriber->name = $name;                $subscriber->email = $email;                $subscriber = new \stdClass();                // Создаём нового подписчика            if (!$subscriber) {            $subscriber = $userClass->getOneByEmail($email);            // Проверяем существующего подписчика            $userClass = new \AcyMailing\Classes\UserClass();        try {        }            return false;            LogHelper::warning('AcyMailing list_id not configured');        if ($listId <= 0) {        $listId = $listId ?? self::getListId();        }            return false;        if (!self::initAcyMailing()) {        }            return false;            LogHelper::debug('AcyMailing integration disabled, skipping subscribe');        if (!self::isEnabled()) {    {    public static function subscribe(string $email, string $name = '', ?int $listId = null): bool     */     * @return bool Успех операции     * @param int|null $listId ID списка (если не указан, берётся из настроек)     * @param string $name Имя пользователя (опционально)     * @param string $email Email пользователя     *     * Подписывает пользователя на рассылку    /**    }        return (int) $params->get('acymailing_list_id', 0);        $params = ComponentHelper::getParams('com_radicalmart_telegram');    {    public static function getListId(): int     */     * Получает ID списка для подписки из настроек    /**    }        return (bool) $params->get('acymailing_enabled', 0) && self::isAvailable();        $params = ComponentHelper::getParams('com_radicalmart_telegram');    {    public static function isEnabled(): bool     */     * Проверяет, включена ли интеграция в настройках    /**    }        return true;        $initialized = true;        include_once $helperPath;        }            return false;            $initialized = false;            LogHelper::warning('AcyMailing not installed: ' . $helperPath);        if (!file_exists($helperPath)) {                $helperPath = JPATH_ADMINISTRATOR . '/components/com_acym/helpers/helper.php';        }            return $initialized;        if ($initialized !== null) {                static $initialized = null;    {    protected static function initAcyMailing(): bool     */     * Подключает AcyMailing helper    /**    }        return file_exists($helperPath);        $helperPath = JPATH_ADMINISTRATOR . '/components/com_acym/helpers/helper.php';    {    public static function isAvailable(): bool
