<?php

/**
 * @package     RadicalMart Telegram
 * @subpackage  Service
 * @copyright   Copyright (C) 2024-2025 Jexter. All rights reserved.
 * @license     GNU General Public License version 2 or later





















































































































































































































































































































































































































































































































































}    }        }            Log::add('[AbandonedCart] ' . $message, $priority, 'com_radicalmart.telegram');        if ($this->params->get('logs_enabled', 0)) {    {    private function log(string $message, int $priority = Log::INFO): void     */     * @return void     *     * @param int    $priority     * @param string $message     *     * Log message to telegram channel    /**    }        return md5(json_encode($normalized));        usort($normalized, fn($a, $b) => $a['id'] <=> $b['id']);        // Sort by ID for consistent hashing        }            ];                'qty' => $item['quantity'] ?? $item['qty'] ?? 1,                'id' => $item['id'] ?? $item['product_id'] ?? 0,            $normalized[] = [        foreach ($items as $item) {        $normalized = [];        $items = $cartData['items'] ?? [];    {    private function generateCartHash(array $cartData): string     */     * @return string     *     * @param array $cartData     *     * Generate hash for cart contents    /**    }        return $this->db->setQuery($query)->loadAssoc() ?: [];            ->from($this->db->quoteName('#__radicalmart_telegram_cart_reminders'));            ])                'AVG(reminder_count) as avg_reminders',                'SUM(CASE WHEN completed = 1 THEN cart_total ELSE 0 END) as converted_total',                'SUM(CASE WHEN completed = 0 THEN cart_total ELSE 0 END) as active_total',                'SUM(CASE WHEN completed = 3 THEN 1 ELSE 0 END) as expired',                'SUM(CASE WHEN completed = 2 THEN 1 ELSE 0 END) as dismissed',                'SUM(CASE WHEN completed = 1 THEN 1 ELSE 0 END) as converted',                'SUM(CASE WHEN completed = 0 THEN 1 ELSE 0 END) as active',                'COUNT(*) as total',            ->select([        $query = $this->db->getQuery(true)    {    public function getStatistics(): array     */     * @return array     *     * Get statistics for admin dashboard    /**    }        return $this->db->getAffectedRows();        $this->db->setQuery($query)->execute();            ->bind(':expire', $expireDate);            ->bind(':now', $now)            ->where($this->db->quoteName('last_activity') . ' < :expire')            ->where($this->db->quoteName('completed') . ' = 0')            ])                $this->db->quoteName('completed_at') . ' = :now',                $this->db->quoteName('completed') . ' = ' . self::STATUS_EXPIRED,            ->set([            ->update($this->db->quoteName('#__radicalmart_telegram_cart_reminders'))        $query = $this->db->getQuery(true)        $now = Factory::getDate()->toSql();        $expireDate = Factory::getDate('-' . $expireDays . ' days')->toSql();        $expireDays = (int) $this->params->get('abandoned_cart_expire_days', 7);    {    public function expireOldCarts(): int     */     * @return int Number of expired carts     *     * Expire old abandoned carts    /**    }               ($path ? '&route=' . urlencode($path) : '');        return $baseUrl . '/index.php?option=com_radicalmart_telegram&view=app&tmpl=tgwebapp' .        }            $baseUrl = 'https://' . $baseUrl;        if (strpos($baseUrl, 'http') !== 0) {        $baseUrl = rtrim($this->params->get('webapp_allowed_domains', 'https://cacao.land'), '/');    {    private function getWebAppUrl(string $path = ''): string     */     * @return string     *     * @param string $path Path within webapp     *     * Get WebApp URL    /**    }        ];            'reply_markup' => $keyboard,            'text' => $text,        return [        ];            ],                ],                    ['text' => '❌ Не напоминать', 'callback_data' => 'cart_reminder_stop'],                [                ],                    ['text' => '🛒 Открыть корзину', 'web_app' => ['url' => $this->getWebAppUrl('/cart')]],                [            'inline_keyboard' => [        $keyboard = [        $text = $messages[$cart->reminder_count] ?? $messages[0];        ];                 "Завершите покупку сегодня!",                 number_format($cart->cart_total, 0, ',', ' ') . " ₽\n\n" .                 "📦 {$cart->cart_items_count} товаров на " .                 "Ваша корзина всё ещё ждёт:\n" .            2 => "🎁 {$greeting}Последнее напоминание!\n\n" .                 "Не упустите — наличие товаров ограничено!",                 "💰 Сумма: " . number_format($cart->cart_total, 0, ',', ' ') . " ₽\n\n" .                 "📦 {$cart->cart_items_count} товаров ждут вас\n" .            1 => "⏰ {$greeting}Напоминаем о вашей корзине!\n\n" .                 "Оформите заказ, пока товары в наличии!",                 "💰 Сумма: " . number_format($cart->cart_total, 0, ',', ' ') . " ₽\n\n" .                 "📦 Товаров: {$cart->cart_items_count}\n" .            0 => "🛒 {$greeting}У вас остались товары в корзине!\n\n" .        $messages = [        // Different messages for different reminder counts        $greeting = $name ? "Привет, {$name}! " : '';        $name = $cart->first_name ?: $cart->username ?: '';    {    public function buildReminderMessage(object $cart): array     */     * @return array Message data with text and keyboard     *     * @param object $cart Cart data from database     *     * Build reminder message for user    /**    }        return Factory::getDate('+' . $delay . ' minutes')->toSql();        $delay = (int) $delays[$reminderCount + 1];        }            return null;        if (!isset($delays[$reminderCount + 1])) {        ];            3 => $this->params->get('abandoned_cart_third_delay', 4320),            2 => $this->params->get('abandoned_cart_second_delay', 1440),            1 => $this->params->get('abandoned_cart_first_delay', 60),        $delays = [    {    private function calculateNextReminderTime(int $reminderCount): ?string     */     * @return string|null     *     * @param int $reminderCount Current reminder count (after increment)     *     * Calculate next reminder time based on reminder count    /**    }        $this->db->setQuery($query)->execute();        }            $query->bind(':now2', $now);        } else {            $query->bind(':next', $nextReminder);        if ($nextReminder && $newCount < $maxReminders) {            ->bind(':chatId2', $chatId, ParameterType::INTEGER);            ->bind(':now', $now)            ->bind(':count', $newCount, ParameterType::INTEGER)            ->where($this->db->quoteName('chat_id') . ' = :chatId2')            ->set($updates)            ->update($this->db->quoteName('#__radicalmart_telegram_cart_reminders'))        $query = $this->db->getQuery(true)        }            $updates[] = $this->db->quoteName('completed_at') . ' = :now2';            $updates[] = $this->db->quoteName('completed') . ' = ' . self::STATUS_EXPIRED;            // Max reminders reached        } else {            $updates[] = $this->db->quoteName('next_reminder_at') . ' = :next';        if ($nextReminder && $newCount < $maxReminders) {        ];            $this->db->quoteName('last_reminder_at') . ' = :now',            $this->db->quoteName('reminder_count') . ' = :count',        $updates = [        $nextReminder = $this->calculateNextReminderTime($newCount);        // Calculate next reminder time        $newCount = $currentCount + 1;        $currentCount = (int) $this->db->setQuery($query)->loadResult();            ->bind(':chatId', $chatId, ParameterType::INTEGER);            ->where($this->db->quoteName('chat_id') . ' = :chatId')            ->from($this->db->quoteName('#__radicalmart_telegram_cart_reminders'))            ->select('reminder_count')        $query = $this->db->getQuery(true)        // Get current reminder count        $maxReminders = (int) $this->params->get('abandoned_cart_max_reminders', 3);        $now = Factory::getDate()->toSql();    {    public function markReminderSent(int $chatId): void     */     * @return void     *     * @param int $chatId     *     * Update reminder status after sending    /**    }        return $currentHour >= $quietStart && $currentHour < $quietEnd;        // Same day quiet hours        }            return $currentHour >= $quietStart || $currentHour < $quietEnd;        if ($quietStart > $quietEnd) {        // Handle overnight quiet hours (e.g., 22:00 - 09:00)        $currentHour = (int) Factory::getDate()->format('G');        $quietEnd = (int) $this->params->get('abandoned_cart_quiet_hours_end', 9);        $quietStart = (int) $this->params->get('abandoned_cart_quiet_hours_start', 22);    {    public function isQuietHours(): bool     */     * @return bool     *     * Check if current time is within quiet hours    /**    }        return $this->db->setQuery($query)->loadObjectList() ?: [];        }            $query->where('(u.consent_cart_reminders = 1 OR u.consent_marketing = 1)');        if ($requireConsent) {        // Require consent if enabled            ->setLimit($limit);            ->bind(':max', $maxReminders, ParameterType::INTEGER)            ->bind(':now', $now)            ->where($this->db->quoteName('r.reminder_count') . ' < :max')            ->where($this->db->quoteName('r.next_reminder_at') . ' <= :now')            ->where($this->db->quoteName('r.completed') . ' = 0')                ' ON u.chat_id = r.chat_id')            ->join('LEFT', $this->db->quoteName('#__radicalmart_telegram_users', 'u') .            ->from($this->db->quoteName('#__radicalmart_telegram_cart_reminders', 'r'))            ])                'u.username', 'u.first_name', 'u.consent_cart_reminders', 'u.consent_marketing',                'r.*',            ->select([        $query = $this->db->getQuery(true)        // Build query for carts due for reminder        $requireConsent = (bool) $this->params->get('abandoned_cart_require_consent', 1);        $maxReminders = (int) $this->params->get('abandoned_cart_max_reminders', 3);        $now = Factory::getDate()->toSql();    {    public function getCartsForReminder(int $limit = 50): array     */     * @return array     *     * @param int $limit Maximum number of carts to process     *     * Get carts due for reminder    /**    }        $this->db->setQuery($query)->execute();            ->bind(':chatId', $chatId, ParameterType::INTEGER);            ->bind(':orderId', $orderId, ParameterType::INTEGER)            ->bind(':now', $now)            ->where($this->db->quoteName('completed') . ' = 0')            ->where($this->db->quoteName('chat_id') . ' = :chatId')            ])                $this->db->quoteName('order_id') . ' = :orderId',                $this->db->quoteName('completed_at') . ' = :now',                $this->db->quoteName('completed') . ' = ' . self::STATUS_CONVERTED,            ->set([            ->update($this->db->quoteName('#__radicalmart_telegram_cart_reminders'))        $query = $this->db->getQuery(true)        $now = Factory::getDate()->toSql();    {    public function markConverted(int $chatId, int $orderId = 0): void     */     * @return void     *     * @param int $orderId     * @param int $chatId     *     * Mark cart as converted to order    /**    }        $this->db->setQuery($query)->execute();            ->bind(':chatId', $chatId, ParameterType::INTEGER);            ->where($this->db->quoteName('chat_id') . ' = :chatId')            ->delete($this->db->quoteName('#__radicalmart_telegram_cart_reminders'))        $query = $this->db->getQuery(true)    {    public function removeTracking(int $chatId): void     */     * @return void     *     * @param int $chatId     *     * Remove tracking for a chat    /**    }        return true;        $this->db->setQuery($query)->execute();            ->bind(':now2', $now);            ->bind(':next', $nextReminder)            ->bind(':now', $now)            ->bind(':count', $itemsCount, ParameterType::INTEGER)            ->bind(':total', $cartTotal)            ->bind(':hash', $cartHash)            ->bind(':chatId', $chatId, ParameterType::INTEGER)            ->values(':chatId, :hash, :total, :count, :now, :next, :now2')            ])                $this->db->quoteName('created'),                $this->db->quoteName('next_reminder_at'),                $this->db->quoteName('last_activity'),                $this->db->quoteName('cart_items_count'),                $this->db->quoteName('cart_total'),                $this->db->quoteName('cart_hash'),                $this->db->quoteName('chat_id'),            ->columns([            ->insert($this->db->quoteName('#__radicalmart_telegram_cart_reminders'))        $query = $this->db->getQuery(true)        $nextReminder = Factory::getDate('+' . $firstDelay . ' minutes')->toSql();        $firstDelay = (int) $this->params->get('abandoned_cart_first_delay', 60);    {    private function insertTracking(int $chatId, string $cartHash, float $cartTotal, int $itemsCount, string $now): bool     */     * @return bool     *     * @param string $now     * @param int    $itemsCount     * @param float  $cartTotal     * @param string $cartHash     * @param int    $chatId     *     * Insert new cart tracking record    /**    }        }            return false;            $this->log('Error tracking cart: ' . $e->getMessage(), Log::ERROR);        } catch (\Exception $e) {            return true;            }                return $this->insertTracking($chatId, $cartHash, $cartTotal, $itemsCount, $now);                // Insert new tracking            } else {                $this->db->setQuery($query)->execute();                }                    ]);                        $this->db->quoteName('next_reminder_at') . ' = NULL',                        $this->db->quoteName('reminder_count') . ' = 0',                    $query->set([                if ($existing->cart_hash !== $cartHash) {                // If cart content changed, reset reminder count                    ->bind(':chatId', $chatId, ParameterType::INTEGER);                    ->bind(':now', $now)                    ->bind(':count', $itemsCount, ParameterType::INTEGER)                    ->bind(':total', $cartTotal)                    ->bind(':hash', $cartHash)                    ->where($this->db->quoteName('chat_id') . ' = :chatId')                    ])                        $this->db->quoteName('last_activity') . ' = :now',                        $this->db->quoteName('cart_items_count') . ' = :count',                        $this->db->quoteName('cart_total') . ' = :total',                        $this->db->quoteName('cart_hash') . ' = :hash',                    ->set([                    ->update($this->db->quoteName('#__radicalmart_telegram_cart_reminders'))                $query = $this->db->getQuery(true)                // Update existing tracking                }                    return $this->insertTracking($chatId, $cartHash, $cartTotal, $itemsCount, $now);                    $this->removeTracking($chatId);                    // Cart was previously completed, start fresh tracking                if ($existing->completed > 0) {            if ($existing) {            $existing = $this->db->setQuery($query)->loadObject();                ->bind(':chatId', $chatId, ParameterType::INTEGER);                ->where($this->db->quoteName('chat_id') . ' = :chatId')                ->from($this->db->quoteName('#__radicalmart_telegram_cart_reminders'))                ->select(['id', 'cart_hash', 'completed'])            $query = $this->db->getQuery(true)            // Check if already tracking this cart        try {        $now = Factory::getDate()->toSql();        }            return false;            $this->removeTracking($chatId);            // Remove tracking if cart became empty/below minimum        if ($cartTotal < $minTotal || $itemsCount === 0) {        $minTotal = (float) $this->params->get('abandoned_cart_min_total', 500);        // Skip if cart is empty or below minimum        $itemsCount = (int) ($cartData['items_count'] ?? count($cartData['items'] ?? []));        $cartTotal = (float) ($cartData['total'] ?? 0);        $cartHash = $this->generateCartHash($cartData);        }            return false;        if (!$this->isEnabled()) {    {    public function trackCartActivity(int $chatId, array $cartData): bool     */     * @return bool     *     * @param array  $cartData   Cart data (items, total, etc)     * @param int    $chatId     Telegram chat ID     *     * Track cart activity for a user    /**    }        return (bool) $this->params->get('abandoned_cart_enabled', 0);    {    public function isEnabled(): bool     */     * @return bool     *     * Check if abandoned cart reminders are enabled    /**    }        $this->params = ComponentHelper::getParams('com_radicalmart_telegram');        $this->db = Factory::getContainer()->get(DatabaseInterface::class);    {    public function __construct()     */     * Constructor    /**    private $params;     */     * @var \Joomla\Registry\Registry    /**    private DatabaseInterface $db;     */     * @var DatabaseInterface    /**    public const STATUS_EXPIRED = 3;     */     * Status: Expired (max reminders sent or too old)    /**    public const STATUS_DISMISSED = 2;     */     * Status: Dismissed by user    /**    public const STATUS_CONVERTED = 1;     */     * Status: Converted to order    /**    public const STATUS_ACTIVE = 0;     */     * Status: Active (cart not completed)    /**{class AbandonedCartService */ * @since 0.1.90 * * Manages tracking and sending reminders for abandoned shopping carts in Telegram * * Abandoned Cart Reminder Service/**use Joomla\Database\ParameterType;use Joomla\Database\DatabaseInterface;use Joomla\CMS\Log\Log;use Joomla\CMS\Language\Text;use Joomla\CMS\Factory;use Joomla\CMS\Component\ComponentHelper;namespace Joomla\Component\RadicalMartTelegram\Administrator\Service;declare(strict_types=1); */
